apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: {{ .Release.Namespace }}
  labels:
    app: load-generator
    app.kubernetes.io/part-of: odimall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
        app.kubernetes.io/part-of: odimall
    spec:
      containers:
        - name: load-generator
          image: wsearle/odimall:load-generator
          imagePullPolicy: Always
          env:
            - name: GATEWAY_URL
              value: "http://api-gateway:8081"
            - name: INTERVAL
              value: "5s"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
