apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: payment-service
    app.kubernetes.io/part-of: odimall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        app.kubernetes.io/part-of: odimall
    spec:
      containers:
        - name: payment-service
          image: wsearle/odimall:payment-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: payment-service
    app.kubernetes.io/part-of: odimall
spec:
  selector:
    app: payment-service
  ports:
    - port: 8086
      targetPort: 8086
