apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: odimall
  labels:
    app: user-service
    app.kubernetes.io/part-of: odimall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        app.kubernetes.io/part-of: odimall
    spec:
      containers:
        - name: user-service
          image: wsearle/odimall:user-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: odimall
  labels:
    app: user-service
    app.kubernetes.io/part-of: odimall
spec:
  selector:
    app: user-service
  ports:
    - port: 8084
      targetPort: 8084
